spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: root
    password: B16@0454ec

server:
  port: 8081

app:
  page-size: 10

stripe:
  url: https://api:stripe:com
  timeout: 3000
  enable: true
  supported-currencies: USD,RUPEES,EUR,DIN

paypal:
  url: https://api:paypal:com
  timeout: 5000
  enable: true
  supported-currencies: USD,RUPEES,EUR,DIN

payment:
  service: paypal

user-service:
  email:
    host: smtp.example.com
    port: 587